name: Continuous Integration & Delivery
on:
  push:
    branches:
      - develop
      - main
      - bugfix/*
      - feature/*
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:
    inputs:
      publish_nuget_package:
        description: Publish a new NuGet package?
        required: false
        type: boolean
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.sha }}'
  cancel-in-progress: true
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_USE_POLLING_FILE_WATCHER: true
  NUGET_XMLDOC_MODE: skip
  TZ: CET
jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
          - ubuntu-22.04
          # - windows-2022
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: ./.github/workflows/actions/tests
  colima:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: ./.github/workflows/actions/install-colima
      - uses: ./.github/workflows/actions/tests
  podman:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: ./.github/workflows/actions/install-podman
      - uses: ./.github/workflows/actions/tests
  publish:
    needs:
      - docker
      - colima
      - podman
    runs-on: ubuntu-22.04
    steps:
      - run: exit 0
